Selective live alert reward notifications
MarkNjunge/helix pull request #1
Opened 2018-08-23 09:10 UTC by Sichangi

Initial implementation for live alerts, ready for testing on slack

2018-08-23 09:19 UTC, Sichangi commented
Commands:

Start Live watch: `/wf alert-watch:start`

Stop Live watch: `/wf alert-watch:stop`

Add a reward: `/wf alert-watch:add:Nitain extract`

Remove a reward: `/wf alert-watch:remove:Nitain extract`

2018-08-23 09:40 UTC, MarkNjunge requested changes

2018-08-23 09:40 UTC, MarkNjunge commented on src/slack/messaging.js
> +      as_user: true,
This should be taken as a parameter.

2018-08-23 09:41 UTC, MarkNjunge commented
I've added a contributing guide, make sure to follow those guidelines.

2018-08-23 09:42 UTC, MarkNjunge commented
Make sure to test your changes before making a pr.

2018-08-23 19:41 UTC, Sichangi commented
Minor tweaks implemented, adherence to lint rules and response updates

2018-08-24 15:12 UTC, MarkNjunge approved these changes

2018-08-31 16:20 UTC, MarkNjunge requested changes

2018-08-31 16:20 UTC, MarkNjunge commented on src/shared/warframe/live/alerts.js
> +const {sendRegularMessage} = require("../../../slack/messaging");
Code specific to Slack should not be here.

2018-08-31 16:20 UTC, MarkNjunge commented on src/slack/warframe.js
> +      text: `Manages your live alert notifications e.g. \`${command} alerts-watch:[start/stop/add/remove]:[reward]\``
Provide more detailed examples, similar to your [second comment](https://github.com/MarkNjunge/helix/pull/1#issuecomment-415349830) in this PR.

2018-09-18 18:20 UTC, MarkNjunge commented
I'm closing this PR since there hasn't been any update. Feel free to re-open it or create another one.

2018-09-18 18:20 UTC, closed without merging